- name: Play Ping
  hosts: lxc_containers:virtual_machines:ansible_controllers:oracle_virtual_machines
  become: yes
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Ping all good!
