- name: Play Ping
  hosts: ansible_controllers:lxc_pihole:lxc_testing:virtual_machines_homeassistant:virtual_machines_wazuh
  become: yes
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Ping all good!
