- name: Clear lancache
  hosts: virtual_machines_homeassistant
  become: yes
  become_user: root
  tasks:
    - name: Remove all files in the cache directory
      ansible.builtin.shell: rm -rf /opt/lancache/cache/cache/*
      args:
        warn: no
