- name: Unconditionally reboot all servers
  hosts: all
  become: yes
  tasks:
    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Scheduled reboot by Ansible"
        connect_timeout: 120
        reboot_timeout: 300
        pre_reboot_delay: 120
        post_reboot_delay: 120
        test_command: whoami