- name: Clear lancache
  hosts: virtual_machines_homeassistant
  become: yes
  become_user: root
  become_method: sudo
  tasks:
   - name: Remove all files in the cache directory
     ansible.builtin.file:
       path: /opt/lancache/cache/cache/
       state: absent
       recurse: yes
   
   - name: Recreate the cache directory
     ansible.builtin.file:
       path: /opt/lancache/cache/cache/
       state: directory
       mode: '0755'
       owner: root
       group: root