- name: Clear lancache
  hosts: virtual_machines_homeassistant
  become: true
  tasks:
    - name: Remove all files in the cache directory
      become: true
      ansible.builtin.shell: rm -rf /opt/lancache/cache/cache/*
